# PowerShell version of run_all
Set-StrictMode -Version Latest
# Run Project A
& "bash" -c "bash Project_A_PreFeature_UI/run_tests.sh"
# Run Project B
& "bash" -c "bash Project_B_PostFeature_UI/run_tests.sh"
# Copy results
New-Item -ItemType Directory -Force -Path shared_artifacts\results
Copy-Item -Path Project_A_PreFeature_UI\results\* -Destination shared_artifacts\results\ -Force -ErrorAction SilentlyContinue
Copy-Item -Path Project_B_PostFeature_UI\results\* -Destination shared_artifacts\results\ -Force -ErrorAction SilentlyContinue

Write-Host "Run complete. See shared_artifacts/compare_report.md (generated by run_all.sh)"
